# Generated by Django 4.1.5 on 2023-01-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cakewale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
